In [1]:
import numpy as np

In [2]:
inp = """#############
#...........#
###C#D#D#A###
  #B#A#B#C#
  #########"""
#12530

In [3]:
corridor = range(7)
inp = inp.replace("D", "4")
inp = inp.replace("C", "3")
inp = inp.replace("B", "2")
inp = inp.replace("A", "1")
pos = inp.replace("#"," ").split("\n")[2:4]
for i in range(len(pos)):
    pos[i] = [int(n) for n in pos[i].strip(" ").split(" ")]
pos = np.array(pos)
pos

array([[3, 4, 4, 1],
       [2, 1, 2, 3]])

In [4]:
if pos[1,3] != 4:
    print("yes")

yes


In [5]:
inp = """#############
#...........#
###B#C#B#D###
  #A#D#C#A#
  #########"""
#12521

# Bruteforce

In [6]:
import copy

In [7]:
inp = inp.replace("D", "4")
inp = inp.replace("C", "3")
inp = inp.replace("B", "2")
inp = inp.replace("A", "1")
inp = inp.replace("#", " ")
split = [n.strip().split(" ") for n in inp.split("\n")[2:4]]
print(split)
pos = [[],[],[],[],[],[],[],[],[],[],[]]
for i in [1,0]:
    for j in range(4): pos[2+2*j] += [int(split[i][j])]
print(pos)

[['2', '3', '2', '4'], ['1', '4', '3', '1']]
[[], [], [1, 2], [], [4, 3], [], [3, 2], [], [1, 4], [], []]


In [9]:
def cost(q,from_here,to_here):
    mult = 10**(q[from_here][-1]-1)
    dist = abs(from_here-to_here)
    if from_here in [2,4,6,8]: dist += 3-len(q[from_here])
    if to_here in [2,4,6,8]: dist += 2-len(q[to_here])
    return dist*mult

In [10]:
def reachable(q,i):
    r = []
    k = i-1
    while True:
        r += [k]
        if k not in [2,4,6,8] and len(q[k]) == 1: break
        elif k == 0: break
        k -= 1
    k = i+1
    while True:
        r += [k]
        if k not in [2,4,6,8] and len(q[k]) == 1: break
        elif k == 10: break
        k += 1
    return r

In [22]:
def solve(q, costs):
    #print("NEW")
    cont = True
    while cont:
        #print(q)
        cont = False
        done = []
        for i in [2,4,6,8]:
            # Check if any stack is finished and fill
            if all([j == i//2 for j in q[:][i]]):
                done += [i]
                r = reachable(q,i)
                for e in r:
                    if len(q[e])>0 and q[e][-1] == i//2:
                        costs += cost(q,e,i)
                        q[i].append(q[e].pop())
                        cont = True
    
    if len(done) == 4 and sum([len(q[n]) for n in range(11) if n not in [2,4,6,8]]) == 0: 
            return q, costs, True
        
    # Expand new paths  
    best_costs = 10**9
    for i in [2,4,6,8]:
        if i not in done:
            r = reachable(q,i)
            for e in r:
                if len(q[e]) == 0 and len(q[i]) > 0 and e not in [2,4,6,8]:
                    new_q = copy.deepcopy(q)
                    new_cost = costs + cost(q,i,e)
                    new_q[e].append(new_q[i].pop())
                    q_alt, costs_alt, finished = solve(new_q, new_cost)
                    if finished: 
                        #print(costs_alt)
                        if costs_alt < best_costs:
                            best_costs = costs_alt
                            best_q = copy.deepcopy(q_alt)
                            
    if best_costs < 10**9:
        return best_q, best_costs, True
    else:            
        return q, costs, False #If nothing worked

In [23]:
#q = [[],[],[1,4],[],[2],[],[3],[],[4,1],[],[]]
q = copy.deepcopy(pos)
q,costs,_ = solve(q, 0)
costs

50492

# Part 2

In [14]:
inp = """#############
#...........#
###B#C#B#D###
  #D#C#B#A#
  #D#B#A#C#
  #A#D#C#A#
  #########"""
#44169

In [18]:
inp = """#############
#...........#
###C#D#D#A###
  #D#C#B#A#
  #D#B#A#C#
  #B#A#B#C#
  #########"""

In [19]:
import numpy as np
import copy

def reachable(q,i):
    r = []
    k = i-1
    while True:
        r += [k]
        if k not in [2,4,6,8] and len(q[k]) == 1: break
        elif k == 0: break
        k -= 1
    k = i+1
    while True:
        r += [k]
        if k not in [2,4,6,8] and len(q[k]) == 1: break
        elif k == 10: break
        k += 1
    return r

def cost(q,from_here,to_here):
    mult = 10**(q[from_here][-1]-1)
    dist = abs(from_here-to_here)
    if from_here in [2,4,6,8]: dist += 5-len(q[from_here])
    if to_here in [2,4,6,8]: dist += 4-len(q[to_here])
    return dist*mult

def solve(q, costs):
    #print("NEW")
    cont = True
    while cont:
        #print(q)
        cont = False
        done = []
        for i in [2,4,6,8]:
            # Check if any stack is finished and fill
            if all([j == i//2 for j in q[:][i]]):
                done += [i]
                r = reachable(q,i)
                for e in r:
                    if len(q[e])>0 and q[e][-1] == i//2:
                        costs += cost(q,e,i)
                        q[i].append(q[e].pop())
                        cont = True
    
    if len(done) == 4 and sum([len(q[n]) for n in range(11) if n not in [2,4,6,8]]) == 0: 
            return q, costs, True
        
    # Expand new paths  
    best_costs = 10**9
    for i in [2,4,6,8]:
        if i not in done:
            r = reachable(q,i)
            for e in r:
                if len(q[e]) == 0 and len(q[i]) > 0 and e not in [2,4,6,8]:
                    new_q = copy.deepcopy(q)
                    new_cost = costs + cost(q,i,e)
                    new_q[e].append(new_q[i].pop())
                    q_alt, costs_alt, finished = solve(new_q, new_cost)
                    if finished: 
                        #print(costs_alt)
                        if costs_alt < best_costs:
                            best_costs = costs_alt
                            best_q = copy.deepcopy(q_alt)
                            
    if best_costs < 10**9:
        return best_q, best_costs, True
    else:            
        return q, costs, False #If nothing worked

In [20]:
inp = inp.replace("D", "4")
inp = inp.replace("C", "3")
inp = inp.replace("B", "2")
inp = inp.replace("A", "1")
inp = inp.replace("#", " ")
split = [n.strip().split(" ") for n in inp.split("\n")[2:6]]
print(split)
pos = [[],[],[],[],[],[],[],[],[],[],[]]
for i in [3,2,1,0]:
    for j in range(4): pos[2+2*j] += [int(split[i][j])]
print(pos)

[['3', '4', '4', '1'], ['4', '3', '2', '1'], ['4', '2', '1', '3'], ['2', '1', '2', '3']]
[[], [], [2, 4, 4, 3], [], [1, 2, 3, 4], [], [2, 1, 2, 4], [], [3, 3, 1, 1], [], []]


In [21]:
#q = [[],[],[1,4],[],[2],[],[3],[],[4,1],[],[]]
q = copy.deepcopy(pos)
q,costs,_ = solve(q, 0)
costs

50492

# Old

In [10]:
def moves(pos, cor, done, costs, solved):
    # test if any step leads to into room (intermediate goal)
    for i in range(4):
        if pos[:,i] in [0,i+1].all():
            done[i] = True
    for j in range(4):
        if done[j]:
            
        
    """
    while True:
        for i in range(7):
            c = cor[i]
            if c != 0:
                for j in range(4):
                    if pos[1,j] == 0 and j+1 == c: 
                        testway
                    elif pos[0,j] == 0 and pos[1,j] = j+1 and j+1 == c:
                        testway
        for i in range(4):
            if pos[0,i] == 0 or pos[0,i] == i+1 and pos[1,i] == 0 or pos[1,i] == i+1:
                continue
            elif pos[0,i] == 0 
            for j in range(4):
                if j != i:    
    """
    
    # add potential moves and positions
    for i in range(4):
        if pos[0,i] == 0 or pos[0,i] == i+1 and pos[1,i] == 0 or pos[1,i] == i+1:
            continue
        else:
            for 
    
    # if no more moves available, check if solved then give out costs
    if solved: print(costs)

IndentationError: expected an indented block (Temp/ipykernel_14868/1339575964.py, line 10)

In [71]:
print(pos)
print(corridor)

[[2 3 2 4]
 [1 4 3 1]]
[0. 0. 0. 0. 0. 0. 0.]
